file( TO_CMAKE_PATH "$ENV{ALLUSERSPROFILE}/chocolatey/" CHOCOLATEY_DIR )
if( EXISTS ${CHOCOLATEY_DIR} )
    set( CHOCO_FOUND TRUE )
endif()

macro(ChocoFind_CURL)
    file( GLOB CHOCO_CURL_DIRS LIST_DIRECTORIES TRUE ${CHOCOLATEY_DIR}/lib/curl/tools/curl-* )
    list( GET CHOCO_CURL_DIRS 0 CHOCO_CURL_DIR )
    list( APPEND CMAKE_PREFIX_PATH ${CHOCO_CURL_DIR} )
    set( CHOCO_CURL_LIB_FILE ${CHOCO_CURL_DIR}/bin/libcurl-x64.dll )
    configure_file( ${CHOCO_CURL_LIB_FILE} ${CMAKE_CURRENT_BINARY_DIR}/libcurl-x64.dll COPYONLY )
endmacro()
