name: RailOSPkgManager
on: [push]
permissions:
  contents: write

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup cmake
      uses: lukka/get-cmake@latest

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 12
        platform: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        version: '6.9.0'
        setup-python: false
        modules: qt5compat

    - name: Install Curl
      run: sudo apt install -y sudo curl libssl-dev libcurl4-openssl-dev

    - name: Build RailOSPackageManager
      env:
        CXX: g++-12
        CC: gcc-12
      run: |
            cmake -Bbuild -DCURL_USE_OPENSSL=ON -G Ninja
            cmake --build build -j 8

  build-test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        version: '6.9.0'
        setup-python: false
        modules: qt5compat
        arch: 'win64_mingw'

    - name: Upgrade GCC
      run: choco upgrade mingw

    - name: Setup cmake
      uses: lukka/get-cmake@latest

    - name: Install CURL
      run: choco install curl

    - name: Install ZLIB
      run: powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat

    - name: Build RailOSPackageManager
      env:
        CXX: g++
        CC: gcc
      run: |
        cmake -Bbuild -DCURL_USE_OPENSSL=ON -G "MinGW Makefiles"
        cmake --build build -j 8
      shell: bash

