name: Generate Repo List Periodically

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-list:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Fetch and filter repositories
              run: |
                  mkdir -p data/
                  curl -s "https://api.github.com/orgs/Railway-Op-Sim/repos?per_page=1000" | jq -r '.[].name' | grep -oE '^\w{2}-.*' > data/github_registry.dat

            - name: Commit data to a separate branch
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  TARGET_BRANCH="registry-data"
                  FILE_TO_COMMIT="data/github_registry.dat"


                  git stash --include-untracked


                  if git show-ref --verify --quiet "refs/remotes/origin/$TARGET_BRANCH"; then
                    echo "Branch $TARGET_BRANCH exists. Switching to it..."
                    git checkout $TARGET_BRANCH
                  else
                    echo "Branch $TARGET_BRANCH does not exist. Creating orphan branch..."
                    
                    git checkout --orphan $TARGET_BRANCH
                    
                    git rm -rf .
                  fi


                  git stash pop || true

                  if [ -f "$FILE_TO_COMMIT" ] && [ -n "$(git status --porcelain $FILE_TO_COMMIT)" ]; then
                    git add $FILE_TO_COMMIT
                    git commit -m "Auto-update: Refresh repository list [skip ci]"
                    git push origin $TARGET_BRANCH
                  else
                    echo "No changes in repository list. Nothing to commit."
                  fi
